Ukraine=Украина
Volodymyr Zelenskyy=Владимир Зеленский
Bees=Пчёлы
Queen Bee=Королева Пчёл
USSR=СССР
Joseph Stalin=Иосиф Сталин
Kazakhstan=Казахстан
Nursultan Nazarbayev=Нурсултан Назарбаев
Belarus=Беларусь
Alexander Lukashenko=Александр Лукашенко
Afghanistan=Афганистан
Ahmad Shah Massoud=Ахмад Шах Масуд
Taiwan=Тайвань
Tsai Ing-wen=Цай Инвэнь
Ranters=Рантеры
Ranter King=Король Рантеров
Predsmertnoe=Предсмертное
Death's Herald=Вестник Смерти
Children=Дети
Little Captain=Маленький Капитан
Adults=Взрослые
Office Worker=Офисный Работник
Teenagers=Подростки
Skateboard Pro=Про Скейтер
Depressive=Депрессивные
Emo King=Эмо Король
Starch=Крахмал
Potato Overlord=Повелитель Картошки
Ants=Муравьи
Ant Queen=Королева Муравьёв