Ukraine=Україна
Volodymyr Zelenskyy=Володимир Зеленський
Bees=Бджоли
Queen Bee=Королева Бджіл
USSR=СРСР
Joseph Stalin=Йосип Сталін
Kazakhstan=Казахстан
Nursultan Nazarbayev=Нурсултан Назарбаєв
Belarus=Білорусь
Alexander Lukashenko=Олександр Лукашенко
Afghanistan=Афганістан
Ahmad Shah Massoud=Ахмад Шах Масуд
Taiwan=Тайвань
Tsai Ing-wen=Цай Інвень
Ranters=Рантери
Ranter King=Король Рантерів
Predsmertnoe=Передсмертне
Death's Herald=Вісник Смерті
Children=Діти
Little Captain=Маленький Капітан
Adults=Дорослі
Office Worker=Офісний Працівник
Teenagers=Підлітки
Skateboard Pro=Про Скейтер
Depressive=Депресивні
Emo King=Емо Король
Starch=Крохмаль
Potato Overlord=Повелитель Картоплі
Ants=Мурахи
Ant Queen=Королева Мурашок